/*
*En este programa se realizara el texto de impresion con caracteres
*@author Ulises Abdiel Cabello Cardenas y Fernanda Muñoz Arroyo
*@version 1
*/
public class feli{
    public static void main(String[] args) {
        // Imprimir "Muchas felicidades Ulises y Adrián!!"
        System.out.print('M');
        System.out.print('u');
        System.out.print('c');
        System.out.print('h');
        System.out.print('a');
        System.out.print('s');
        System.out.print(' ');
        System.out.print('f');
        System.out.print('e');
        System.out.print('l');
        System.out.print('i');
        System.out.print('c');
        System.out.print('i');
        System.out.print('d');
        System.out.print('a');
        System.out.print('d');
        System.out.print('e');
        System.out.print('s');
        System.out.print(' ');
        System.out.print('U');
        System.out.print('l');
        System.out.print('i');
        System.out.print('s');
        System.out.print('e');
        System.out.print('s');
        System.out.print(' ');
        System.out.print('y');
        System.out.print(' ');
        System.out.print('A');
        System.out.print('d');
        System.out.print('r');
        System.out.print('i');
        System.out.print('a');
        System.out.print('n');
        System.out.print('!');
        System.out.print('!');
        System.out.print('\n');

        // Imprimir "En la facultad estamos que no cabemos de gusto y orgullo por que están aprendiendo"
        System.out.print('E');
        System.out.print('n');
        System.out.print(' ');
        System.out.print('l');
        System.out.print('a');
        System.out.print(' ');
        System.out.print('f');
        System.out.print('a');
        System.out.print('c');
        System.out.print('u');
        System.out.print('l');
        System.out.print('t');
        System.out.print('a');
        System.out.print('d');
        System.out.print(' ');
        System.out.print('e');
        System.out.print('s');
        System.out.print('t');
        System.out.print('a');
        System.out.print('m');
        System.out.print('o');
        System.out.print('s');
        System.out.print(' ');
        System.out.print('q');
        System.out.print('u');
        System.out.print('e');
        System.out.print(' ');
        System.out.print('n');
        System.out.print('o');
        System.out.print(' ');
        System.out.print('c');
        System.out.print('a');
        System.out.print('b');
        System.out.print('e');
        System.out.print('m');
        System.out.print('o');
        System.out.print('s');
        System.out.print(' ');
        System.out.print('d');
        System.out.print('e');
        System.out.print(' ');
        System.out.print('g');
        System.out.print('u');
        System.out.print('s');
        System.out.print('t');
        System.out.print('o');
        System.out.print(' ');
        System.out.print('y');
        System.out.print(' ');
        System.out.print('o');
        System.out.print('r');
        System.out.print('g');
        System.out.print('u');
        System.out.print('l');
        System.out.print('l');
        System.out.print('o');
        System.out.print(' ');
        System.out.print('p');
        System.out.print('o');
        System.out.print('r');
        System.out.print(' ');
        System.out.print('q');
        System.out.print('u');
        System.out.print('e');
        System.out.print(' ');
        System.out.print('e');
        System.out.print('s');
        System.out.print('t');
        System.out.print('á');
        System.out.print('n');
        System.out.print(' ');
        System.out.print('a');
        System.out.print('p');
        System.out.print('r');
        System.out.print('e');
        System.out.print('n');
        System.out.print('d');
        System.out.print('i');
        System.out.print('e');
        System.out.print('n');
        System.out.print('d');
        System.out.print('o');
        System.out.print('\n');

        // Imprimir "a programar en Java con orientación a objetos."
        System.out.print('a');
        System.out.print(' ');
        System.out.print('p');
        System.out.print('r');
        System.out.print('o');
        System.out.print('g');
        System.out.print('r');
        System.out.print('a');
        System.out.print('m');
        System.out.print('a');
        System.out.print('r');
        System.out.print(' ');
        System.out.print('e');
        System.out.print('n');
        System.out.print(' ');
        System.out.print('J');
        System.out.print('a');
        System.out.print('v');
        System.out.print('a');
        System.out.print(' ');
        System.out.print('c');
        System.out.print('o');
        System.out.print('n');
        System.out.print(' ');
        System.out.print('o');
        System.out.print('r');
        System.out.print('i');
        System.out.print('e');
        System.out.print('n');
        System.out.print('t');
        System.out.print('a');
        System.out.print('c');
        System.out.print('i');
        System.out.print('ó');
        System.out.print('n');
        System.out.print(' ');
        System.out.print('a');
        System.out.print(' ');
        System.out.print('o');
        System.out.print('b');
        System.out.print('j');
        System.out.print('e');
        System.out.print('t');
        System.out.print('o');
        System.out.print('s');
        System.out.print('.');
        System.out.print('\n');

        // Imprimir "De verdad 'Muchas felicidades!!'"
        System.out.print('D');
        System.out.print('e');
        System.out.print(' ');
        System.out.print('v');
        System.out.print('e');
        System.out.print('r');
        System.out.print('d');
        System.out.print('a');
        System.out.print('d');
        System.out.print(' ');
        System.out.print('"');
        System.out.print('M');
        System.out.print('u');
        System.out.print('c');
        System.out.print('h');
        System.out.print('a');
        System.out.print('s');
        System.out.print(' ');
        System.out.print('f');
        System.out.print('e');
        System.out.print('l');
        System.out.print('i');
        System.out.print('c');
        System.out.print('i');
        System.out.print('d');
        System.out.print('a');
        System.out.print('d');
        System.out.print('e');
        System.out.print('s');
        System.out.print('!');
        System.out.print('!');
        System.out.print('"');
        System.out.print('\n');

        // Imprimir "Un abrazo :)"
        System.out.print('U');
        System.out.print('n');
        System.out.print(' ');
        System.out.print('a');
        System.out.print('b');
        System.out.print('r');
        System.out.print('a');
        System.out.print('z');
        System.out.print('o');
        System.out.print(' ');
        System.out.print(':');
        System.out.print(')');
    }
}
